const { contextBridge, ipcRenderer } = require('electron')
contextBridge.exposeInMainWorld('toolbox', {
  launch: (target, options) => ipcRenderer.invoke('toolbox:launch', target, options),
  chooseItemImage: () => ipcRenderer.invoke('toolbox:choose-item-image'),
  exportSource: (sourceId) => ipcRenderer.invoke('toolbox:export-source', sourceId),
  chooseConfigImport: () => ipcRenderer.invoke('toolbox:choose-config-import'),
  getToolPackStatus: () => ipcRenderer.invoke('toolbox:get-tool-pack-status'),
  chooseToolPack: () => ipcRenderer.invoke('toolbox:choose-tool-pack'),
  installToolPack: (sourcePath) => ipcRenderer.invoke('toolbox:install-tool-pack', sourcePath),
  downloadToolPack: () => ipcRenderer.invoke('toolbox:download-tool-pack'),
  importConfig: (payload) => ipcRenderer.invoke('toolbox:import-config', payload),
  getBackgroundSettings: () => ipcRenderer.invoke('toolbox:get-background-settings'),
  saveBackground: (payload) => ipcRenderer.invoke('toolbox:save-background', payload),
  selectBackground: (image) => ipcRenderer.invoke('toolbox:select-background', image),
  resetBackground: () => ipcRenderer.invoke('toolbox:reset-background'),
  getAnnouncement: () => ipcRenderer.invoke('toolbox:get-announcement'),
  dismissAnnouncement: (contentId) => ipcRenderer.invoke('toolbox:dismiss-announcement', contentId),
  getUpdateState: () => ipcRenderer.invoke('toolbox:get-update-state'),
  getUpdateSettings: () => ipcRenderer.invoke('toolbox:get-update-settings'),
  saveUpdateSettings: (settings) => ipcRenderer.invoke('toolbox:save-update-settings', settings),
  checkForUpdates: () => ipcRenderer.invoke('toolbox:check-for-updates'),
  downloadUpdate: () => ipcRenderer.invoke('toolbox:download-update'),
  installUpdate: () => ipcRenderer.invoke('toolbox:install-update'),
  onUpdateStatus: (callback) => ipcRenderer.on('toolbox:update-status', (_event, state) => callback(state)),
  getRuntimeLogs: (limit) => ipcRenderer.invoke('toolbox:get-runtime-logs', limit),
  exportRuntimeLogs: () => ipcRenderer.invoke('toolbox:export-runtime-logs'),
  logRendererEvent: (payload) => ipcRenderer.invoke('toolbox:log-renderer-event', payload),
  onRuntimeLog: (callback) => { const listener = (_event, entry) => callback(entry); ipcRenderer.on('toolbox:runtime-log', listener); return () => ipcRenderer.removeListener('toolbox:runtime-log', listener) },
  listSources: () => ipcRenderer.invoke('toolbox:list-sources'),
  createSource: (source) => ipcRenderer.invoke('toolbox:create-source', source),
  switchSource: (sourceId) => ipcRenderer.invoke('toolbox:switch-source', sourceId),
  deleteSource: (sourceId) => ipcRenderer.invoke('toolbox:delete-source', sourceId),
  listCategories: (sourceId) => ipcRenderer.invoke('toolbox:list-categories', sourceId),
  saveCategories: (sourceId, categories) => ipcRenderer.invoke('toolbox:save-categories', sourceId, categories),
  listItems: (sourceId) => ipcRenderer.invoke('toolbox:list-items', sourceId),
  saveItemOrder: (sourceId, ids) => ipcRenderer.invoke('toolbox:save-item-order', sourceId, ids),
  saveItem: (item) => ipcRenderer.invoke('toolbox:save-item', item),
  deleteItem: (sourceId, id) => ipcRenderer.invoke('toolbox:delete-item', sourceId, id),
  bulkUpdateItems: (payload) => ipcRenderer.invoke('toolbox:bulk-update-items', payload),
  importItemToSource: (payload) => ipcRenderer.invoke('toolbox:import-item-to-source', payload),
  chooseBackground: () => ipcRenderer.invoke('toolbox:choose-background'),
  listSchedules: () => ipcRenderer.invoke('toolbox:list-schedules'),
  saveSchedule: (schedule) => ipcRenderer.invoke('toolbox:save-schedule', schedule),
  deleteSchedule: (id) => ipcRenderer.invoke('toolbox:delete-schedule', id),
  runSchedule: (id) => ipcRenderer.invoke('toolbox:run-schedule', id),
  getShortcuts: () => ipcRenderer.invoke('toolbox:get-shortcuts'),
  getWheelLayout: (sourceId) => ipcRenderer.invoke('toolbox:get-wheel-layout', sourceId),
  saveShortcuts: (settings) => ipcRenderer.invoke('toolbox:save-shortcuts', settings),
  previewWheel: (appearance) => ipcRenderer.invoke('toolbox:preview-wheel', appearance),
  launchWheelItem: (id) => ipcRenderer.invoke('toolbox:wheel-launch', id),
  hideWheel: () => ipcRenderer.send('toolbox:wheel-hide'),
  onWheelData: (callback) => ipcRenderer.on('wheel:data', (_event, data) => callback(data)),
})
